# Generated by Django 4.1.4 on 2023-03-04 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
