# Generated by Django 4.2 on 2023-05-15 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmsg',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
