# Generated by Django 4.1.4 on 2023-05-21 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0002_alter_itemmsg_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(default='/albums-thumbnails/default.png', upload_to='albums-thumbnails'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
