# Generated by Django 4.1.4 on 2023-05-21 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0004_item_time_created_alter_item_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
