# Generated by Django 4.1.4 on 2023-05-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0005_alter_item_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time_created',
        ),
    ]
