# Generated by Django 4.1.4 on 2023-05-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0007_item_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
    ]
