# Generated by Django 4.1.4 on 2023-05-23 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0008_remove_item_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=48)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='love.item')),
            ],
        ),
    ]
