# Generated by Django 4.1.4 on 2023-05-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0009_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'permissions': [('view_album', 'Can view album')]},
        ),
    ]
