# Generated by Django 4.1.4 on 2023-05-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('love', '0012_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='where',
            field=models.CharField(default='CAN_FIND', max_length=24),
        ),
    ]
