# Generated by Django 4.1.4 on 2023-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default='None', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='None', max_length=5),
        ),
    ]
