# Generated by Django 4.1.4 on 2023-04-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stogit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stogitgame',
            name='cardsUsed',
            field=models.CharField(default='', max_length=1000000),
        ),
        migrations.CreateModel(
            name='StogitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.CharField(max_length=120000)),
                ('status', models.CharField(max_length=24)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stogit.stogitplayer')),
            ],
        ),
    ]
