# Generated by Django 4.1.4 on 2023-04-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stogit', '0002_stogitgame_cardsused_stogitstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='stogitplayer',
            name='connected',
            field=models.CharField(default='True', max_length=12),
        ),
    ]
