# Generated by Django 4.1.4 on 2023-04-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stogit', '0007_alter_stogitstatus_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stogitstatus',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
