# Generated by Django 4.1.4 on 2023-04-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stogit', '0008_alter_stogitstatus_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='stogitround',
            name='votedCard',
            field=models.CharField(default='', max_length=4),
        ),
    ]
