# Generated by Django 4.1.4 on 2023-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stogit', '0009_stogitround_votedcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stogitround',
            old_name='truecard',
            new_name='story',
        ),
        migrations.AlterField(
            model_name='stogitplayer',
            name='connected',
            field=models.CharField(default='False', max_length=12),
        ),
    ]
