# Generated by Django 4.1.4 on 2023-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stogit', '0010_rename_truecard_stogitround_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stogitstats',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stogitstats',
            name='most_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stogitstats',
            name='rank_role',
            field=models.CharField(default='Novice', max_length=12),
        ),
        migrations.AlterField(
            model_name='stogitstats',
            name='total_points',
            field=models.IntegerField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='stogitstats',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stogitstats',
            name='wins_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stogitstatus',
            name='status',
            field=models.CharField(max_length=48),
        ),
    ]
